development: 
  cloud_name: "de5bgmb1t"
  api_key: "727852849549781"
  api_secret: "jTiNwQQh9S23w_J4npEFPKb5AFU"
  secure: true

production:
  cloud_name: "de5bgmb1t"
  api_key: "727852849549781"
  api_secret: "jTiNwQQh9S23w_J4npEFPKb5AFU"
  secure: true